### PR TITLE
Adding noAttributesWithArrayNotation option

### PR DESCRIPTION
**Pull request by nkwwk**

### CODE REVIEW

**Comment by therealparmesh** [comment]
Can you expand on when this is needed? I seems like arrays are being flattened here, more or less.

**Comment by nkwwk** [comment]
Currently, the plugin seems only available file array to remove the array notation instead of attributes. If we send the file with `noFilesWithArrayNotation` also an array of attributes, there isn't consistency.

**Comment by therealparmesh** [comment]
I’ll take a look at this. Thanks!

**Comment by HartiganHM** [comment]
@therealparmesh Can we get another look at this PR? This is a blocker for our use case and if it isn't resolved we'll be using another package. Just wanted to chime in since we do love the work here, but this is an edge case we need resolved to keep using it 😄

**Comment by therealparmesh** [comment]
This fell off of my radar. Code looks great and there's test coverage, so let's see if I can bring this in very soon.

**Comment by therealparmesh** [comment]
Published! Thank you!

**Pull request merged**
