### PR TITLE
Filter `undefined` values

### PR DESCRIPTION
**Pull request by piranna**
This is an improvement of #4.

### CODE REVIEW

**Comment by therealparmesh** [comment]
Good work!

**Comment by therealparmesh** [comment]
I brought the gist of this in with my latest commit.

**Comment by piranna** [comment]
There's no changes history, just a single commit. Are you doing append and push force on the code repo? That's no sense...

**Comment by therealparmesh** [comment]
Yes, I decided to rewrite history to start from a point where we have tests. This way we can cleanly see the changes in functionality and fixes for bugs. I don't think the previous history was of much use because this was basically a personal gist that I made public without giving it the proper infrastructure (like tests) that a real package should have. 😄 

Thank you for contributing the fix, and correctly pointing out the difference between `undefined` and `null` when it comes to `FormData`. 💯

**Comment by piranna** [comment]
You are welcome :-)

**Pull request closed without merging**
