### PR TITLE
Adding allowEmptyArrays option

### PR DESCRIPTION
**Pull request by zack-hable**
Hello,

I'd like to add a small flag to allow for us to keep empty arrays in the outputted FormData.  I tried to follow your style, but if you feel the change isn't worthwhile or something needs changed please let me know.

### CODE REVIEW

**Comment by FelipeSanchezCalzada** [comment]
This functionality would be great, I have needed it several times. Is it necessary to do something else to merge?

**Comment by zack-hable** [comment]
@therealparmesh would it be possible for you to review this PR?

@FelipeSanchezCalzada im waiting for the package maintainer to respond, you can manually pull from my repo if needed, but that’s not too ideal/nice with NPM

**Comment by jackson-dikey** [comment]
I also need this functionality!
@therealparmesh please, merge thip PR!  ^__^

**Comment by therealparmesh** [comment]
Can you add tests to keep this at 100% coverage?

**Comment by zack-hable** [comment]
@therealparmesh No problem.  I've added a single test for the case where there is an empty array in the input and the flag is enabled.  Output of ```npm run test```
```
PASS  src/index.test.js
  √ undefined (4ms)
  √ null (4ms)
  √ null with nullsAsUndefineds option
  √ boolean (2ms)
  √ boolean with booleansAsIntegers option (2ms)
  √ integer (1ms)
  √ float
  √ string
  √ empty string (2ms)
  √ Object (2ms)
  √ empty Object (1ms)
  √ Object in Array (1ms)
  √ Object in Object (1ms)
  √ Array (2ms)
  √ empty Array (1ms)
  √ Array in Array (1ms)
  √ Array in Object (2ms)
  √ Array where key ends with "[]" (2ms)
  √ Array with indices option (1ms)
  √ Array with allowEmptyArrays option (2ms)
  √ Date (1ms)
  √ File (3ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 index.js |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time:        3.261s
Ran all test suites.
```

**Comment by therealparmesh** [comment]
Check out the latest version!

**Pull request merged**
